### ISSUE TITLE
Chunkloading not working properly

### ISSUE THREAD

**Issue by Souperhero** [SlowKidsAtPlay/SKaP-Craft#3]
Seems like FTB utilities chunkloading isnt functioning properly, perhaps a quick config check?

\MC.Eternal\config
line 121 & 122

    # Enables chunk loading. If chunk_claiming is set to false, changing this won't do anything.
    B:chunk_loading=true

**Comment by SlowKidsAtPlay** [comment]
disabled until i can correct lag. once tps is stable i will enable it again.until then the chunks you load around you should be enough
