### ISSUE TITLE
Quantum Quarry isn't working

### ISSUE THREAD

**Issue by Orbitus2001** [SlowKidsAtPlay/SKaP-Craft#8]
No matter what I do, redstone on, off, ignore redstone, add a dimension to it, it won't run.  

So, I don't know if the dimension that it would be pulling from can't run because of no chunkloading or what.

**Comment by Souperhero** [comment]
![Screenshot](https://user-images.githubusercontent.com/10240783/74544490-39bfcc80-4f15-11ea-982f-2aa66058c0b2.png)

They should probably disallowed from being placed and used until further testing

**Comment by SlowKidsAtPlay** [comment]
recipe removed
